name:      problem-counter
version:   0.2.0
author:    Evan Relf <evan@evanrelf.com>
homepage:  https://gitlab.com/evanrelf/problem-counter
license:   ISC
copyright: 2018 Evan Relf
category:  Math

dependencies:
  - base >= 4.7 && < 5
  - megaparsec

executables:
  problem-counter:
    source-dirs: src
    main: Main.hs
